### ISSUE TITLE
SQLAlchemy Session issue

### ISSUE THREAD

**Issue by ejabu** [0xTheProDev/fastapi-clean-example#4]
Hi , I came a lot of Fast-api project template and came accross to this [issue](https://github.com/tiangolo/full-stack-fastapi-postgresql/issues/104#issuecomment-586466934)

```
def get_db_connection():
    db = scoped_session(SessionLocal)
    try:
        yield db
    finally:
        db.close()
```

I was wondering, whether this approach already considers issues like [this](https://github.com/tiangolo/full-stack-fastapi-postgresql/issues/290#issuecomment-723155540) and [this](https://github.com/tiangolo/full-stack-fastapi-postgresql/issues/290#issue-717219384) ?

**Comment by Progyan1997** [comment]
I don't think I have made any concious choices around this, let me check and get back to you on this. Great things you pointed out :clap:
