### ISSUE TITLE
question on service-to-service

### ISSUE THREAD

**Issue by Murtagy** [0xTheProDev/fastapi-clean-example#6]
Is it an issue that we expose models directly? For example in BookService we expose model in get method, and we also use models of Author repository.
This implies that we are allowed to use those interfaces - CRUD, read all properties, call other relations, etc.
Is exposing schemas objects between domains is a better solution?

**Comment by 0xTheProDev** [comment]
@Murtagy Very good question, and I apologize for such a delayed response. I would ideally expect a separate strict contract between Service layer and the Web layer. However, for simplicity reason, I have chosen to keep it identical as POJO Model.
