### ISSUE TITLE
What  naming convention is used in this project

### ISSUE THREAD

**Issue by Wrufesh** [0xTheProDev/fastapi-clean-example#7]
Hi,

It would be great if you could clarify the naming convention used in the project for naming class, methods and variables.

**Comment by 0xTheProDev** [comment]
Class -> Upper Camel Case
Instance -> Lower Camel Case
Variable and Methods -> Snake Case

Note that this might and will depend upon teams and orgs implementing this design pattern.

**Comment by Wrufesh** [comment]
Thank you for your reply. 

All variable are instances or some types.

So kind of confused with lower camel case and snake case.
