### ISSUE TITLE
Testing the repository, service layer and suggestions on how to test routes.

### ISSUE THREAD

**Issue by obioma-Nwosu** [0xTheProDev/fastapi-clean-example#8]
Dear Progyan,

I am writing to inquire about your approach to testing the FastAPI clean code project. I have a similar project and I am writing unit tests and integration tests for it. However, testing the repository layer and service layer has been challenging for me.

I saw how you implemented tests in this project, and  you assert if the repository functions are called once, but do not assert what the function call returns. Could you please explain why you took this approach?

You also did something similar in the service layer. I am curious to know why you chose this approach instead of testing the return values and expected results at least in the service layer.

How would you suggest i test the service layer against some expected results, using the (Given, When, Then) approach? and also your suggestions on how to test the routes/endpoints

Thank you for your time

**Comment by 0xTheProDev** [comment]
Hi @obioma-Nwosu 

Thanks for taking interest on the repository and thanks for taking time to write this.

I believe I have made some opinionated choices when comes to testing the application. What I have decided here is to ensure the right set of ops are executed for a particular service, and a contract is validated. The problem with validating against value where external driver (e.g., Database) is present is that I first have to mock or stub the external driver with generated values and then check if those values are coming about. This I am not against but seems like far fetched approach to do a simple thing.

As for testing controller and/or resolver. My opinion or preference is to test them twice. Once as a unit,  by mocking or stubbing the service layer and then ensuring the API contract is being respected. One can even go further and validate against function call to services, but that becomes testing implementation details and potentially couples the test with the working internals. And second as the interface toward the whole system, where we should be having a test database seeded with arbitary yet constrained dataset and execute upon from an external factor (e.g., an E2E test framework).

Let me know if I have given you satisfactory answer or feel free to continue the discussion on this thread.
