### ISSUE TITLE
Incomplete Testing

### ISSUE THREAD

**Issue by syed-bilal-bukhari** [0xTheProDev/fastapi-clean-example#9]
Hi there, Currently I've seen that it have very limited testing, usually all of the functions are just checked if they are being called however, in real scenarios, It is not sufficient.

**Comment by 0xTheProDev** [comment]
Hi @syed-bilal-bukhari, thanks for pointing out. However, this being a merely template, I do not sense much of an urgency in divulging into detailed testing scenarios. Feel free to drop in PR if you have one.
